[service]
host = "localhost"
port = 8080

[webhook]
url = ""

[ifttt_webhook]
url = ""

[slack_webhook]
url = ""

[inspec]
min_impact_to_notify = 0.7

[automate]
enable_forwarding = false
url = "https://<autmoate>/data-collector/v0"
token = "<token>"
