[service]
{{~#if cfg.service.host}}
host = "{{cfg.service.host}}"
{{~else}}
host = "{{sys.ip}}"
{{~/if}}
port = {{cfg.service.port}}

[webhook]
url = "{{cfg.webhook.url}}"

[ifttt_webhook]
url = "{{cfg.ifttt_webhook.url}}"

[slack_webhook]
url = "{{cfg.slack_webhook.url}}"
